module.exports = (
	success = 0,
	errNoUserName = -1000,
	errNoPassword = -1001,
	errNoEmail = -1002,
	errLogin = -1003,
	errInner = -1004,
	errUserExist = -1005,
	errToken = -1006,
	errMysql = -1007,
	errNoOrder = -1008,
	errNoSignupCode = -1009,
	errSignupCode = -1010,
	errUserNotExist = -1011,
	errVerifyCodeTimeout = -1012,
	errVerifyCodeNotRight = -1013,
	errNoVerifyCode = -1014,
	errUserNotMatch = -1015,
	errNoUpdatedUserName = -1016,
	errNoQueriedUserName = -1017,
	errPasswordNotRight = -1018,
	errOrderIdExist = -1019,

	{
		success: 'success',
		errNoUserName: 'userName not found',
		errNoPassword: 'password not found',
		errNoEmail: 'email not found',
		errLogin: 'userName or password not right',
		errInner: 'inner error',
		errUserExist: 'user already exist',
		errToken: 'token not right',
		errNoOrder: 'order not found',
		errNoSignupCode: 'signup code not found',
		errSignupCode: 'signup code not right',
		errUserNotExist: 'user not exist',
		errVerifyCodeTimeout: 'verifyCode timeout',
		errVerifyCodeNotRight: 'verifyCode not right',
		errNoVerifyCode: 'verifyCode not found',
		errUserNotMatch: 'user not match',
		errNoUpdatedUserName: 'updatedUserName not found',
		errNoQueriedUserName: 'queriedUserName not found',
		errPasswordNotRight: 'password not right',
		errOrderIdExist: 'order already exist',
	}
)